name: "taskmaster"
services:
  api:
    build:
      context: ./api
      dockerfile: ../docker/api.dockerfile
      target: app
    ports:
      - 8001:8001
    env_file: .env
    environment:
      - PSQL_CONNECTION_STRING=postgresql+asyncpg://taskmaster:password@db/taskmaster
    command: "sh scripts/launch-api.local.sh"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - redis
  lint:
    image: taskmaster-api
    env_file: .env
    command: "sh scripts/lint.sh"
    profiles: [ "test" ]
    volumes:
      - ./api:/usr/src/app
  test:
    image: taskmaster-api
    env_file: .env
    command: "sh scripts/test.sh"
    environment:
      - PSQL_CONNECTION_STRING=postgresql+asyncpg://taskmaster:password@db/taskmaster
    profiles: [ "test" ]
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - redis
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=taskmaster
    ports:
      - "5432:5432"
