"""create tasks table

Revision ID: 262e4fb05bd7
Revises:
Create Date: 2024-05-13 12:48:22.156679

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "262e4fb05bd7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "scheduled",
                "finished",
                "dropped",
                "overdue",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("scheduled_time", sa.Time(), nullable=True),
        sa.Column("estimated_effort_hours", sa.Float(), nullable=True),
        sa.Column("must_be_done", sa.Boolean(), nullable=False),
        sa.Column(
            "task_mood",
            sa.Enum(
                "very_stressed",
                "stressed",
                "uncomfortable",
                "neutral",
                "good",
                "excited",
                "very_excited",
                name="taskmood",
            ),
            nullable=False,
        ),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
